"""
Forest Fire Recognition System
Main Flask Application

A professional web application for recognizing forest fires
from uploaded images, live camera feeds, and more.
"""

import os
import uuid
import json
import threading
import time
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime

from flask import (
    Flask, render_template, request, jsonify,
    send_file, Response, redirect, url_for
)
from werkzeug.utils import secure_filename
import cv2
import numpy as np
import urllib.request
import urllib.parse
import csv
import io

from utils.preprocess import load_and_preprocess, preprocess_frame
from utils.prediction import predict

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
UPLOAD_DIR = os.path.join(BASE_DIR, "static", "uploads")
DATA_DIR = os.path.join(BASE_DIR, "data")
MODEL_DIR = os.path.join(BASE_DIR, "models")

ALLOWED_EXTENSIONS = {"png", "jpg", "jpeg", "gif", "bmp", "webp"}

app = Flask(__name__)
app.config["MAX_CONTENT_LENGTH"] = 16 * 1024 * 1024  # 16 MB

# Ensure required folders exist
for d in [UPLOAD_DIR, DATA_DIR]:
    os.makedirs(d, exist_ok=True)

# ---------------------------------------------------------------------------
# History helpers (JSON-based persistence)
# ---------------------------------------------------------------------------
HISTORY_FILE = os.path.join(DATA_DIR, "history.json")
_history_lock = threading.Lock()


def _load_history() -> list:
    if os.path.exists(HISTORY_FILE):
        with open(HISTORY_FILE, "r") as fh:
            return json.load(fh)
    return []


def _save_history(records: list):
    with open(HISTORY_FILE, "w") as fh:
        json.dump(records, fh, indent=2)


def _add_record(record: dict):
    with _history_lock:
        records = _load_history()
        records.insert(0, record)
        records = records[:200]  # keep latest 200
        _save_history(records)


# ---------------------------------------------------------------------------
# Camera state
# ---------------------------------------------------------------------------
_cam_active = False
_cam_thread = None
_cam_lock = threading.Lock()

# ---------------------------------------------------------------------------
# Helper
# ---------------------------------------------------------------------------


def _allowed(filename: str) -> bool:
    return "." in filename and filename.rsplit(".", 1)[1].lower() in ALLOWED_EXTENSIONS


def _generate_report(record: dict) -> str:
    sep = "=" * 56
    loc = record.get("location", {})
    location_lines = []
    if loc.get("lat"):
        location_lines = [
            f"  Latitude        : {loc['lat']}",
            f"  Longitude       : {loc['lng']}",
            f"  Address         : {loc.get('address', 'Unknown')}",
        ]
    lines = [
        sep,
        "  FOREST FIRE RECOGNITION — ANALYSIS REPORT",
        sep,
        f"  Detection ID   : {record['id']}",
        f"  Date / Time    : {record['timestamp']}",
        f"  Source File     : {record.get('filename', 'N/A')}",
        sep,
        f"  Prediction      : {record['label']}",
        f"  Detail Class    : {record['detailed_label']}",
        f"  Confidence      : {record['confidence']:.1f}%",
        f"  Risk Level      : {record['risk_level']}",
        sep,
        *location_lines,
        *([ sep ] if location_lines else []),
        "  Class Probabilities:",
        f"    Fire   : {record['probabilities']['fire']:.1f}%",
        f"    Smoke  : {record['probabilities']['smoke']:.1f}%",
        f"    No Fire: {record['probabilities']['no_fire']:.1f}%",
        sep,
        f"  Recommendation  : {record['recommendation']}",
        sep,
        "  Report generated by Forest Fire Recognition System",
        sep,
    ]
    return "\n".join(lines)


# ===================================================================
# ROUTES — Pages
# ===================================================================

@app.route("/")
def home():
    return render_template("index.html")


@app.route("/about")
def about():
    return render_template("about.html")


@app.route("/dataset")
def dataset():
    return render_template("dataset.html")


@app.route("/upload")
def upload_page():
    return render_template("upload.html")


@app.route("/camera")
def camera_page():
    return render_template("camera.html")


@app.route("/dashboard")
def dashboard_page():
    return render_template("dashboard.html")


@app.route("/history")
def history_page():
    return render_template("history.html")


@app.route("/result/<record_id>")
def result_page(record_id):
    records = _load_history()
    record = next((r for r in records if r["id"] == record_id), None)
    if record is None:
        return render_template("index.html"), 404
    return render_template("result.html", record=record)


# ===================================================================
# ROUTES — Detection
# ===================================================================

@app.route("/predict", methods=["POST"])
def predict_image():
    """Handle image upload, run detection, redirect to result page."""
    if "image" not in request.files:
        return jsonify({"error": "No file uploaded"}), 400

    file = request.files["image"]
    if file.filename == "" or not _allowed(file.filename):
        return jsonify({"error": "Invalid file type"}), 400

    ext = file.filename.rsplit(".", 1)[1].lower()
    unique_name = f"{uuid.uuid4().hex}.{ext}"
    save_path = os.path.join(UPLOAD_DIR, unique_name)
    file.save(save_path)

    batch, _ = load_and_preprocess(save_path)
    if batch is None:
        return jsonify({"error": "Could not process image"}), 400

    result = predict(batch, image_path=save_path)

    # Collect geolocation if provided by the browser
    location = {}
    lat = request.form.get("latitude")
    lng = request.form.get("longitude")
    if lat and lng:
        try:
            location = {
                "lat": float(lat),
                "lng": float(lng),
                "address": request.form.get("address", "Unknown"),
            }
        except (ValueError, TypeError):
            pass

    record = {
        "id": uuid.uuid4().hex[:12],
        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "filename": secure_filename(file.filename),
        "image": unique_name,
        "source": "upload",
        "location": location,
        **result,
    }
    _add_record(record)

    return jsonify({"redirect": url_for("result_page", record_id=record["id"]), **record})


# ===================================================================
# ROUTES — Camera
# ===================================================================

def _camera_loop():
    global _cam_active
    cap = cv2.VideoCapture(0)
    if not cap.isOpened():
        _cam_active = False
        return
    while _cam_active:
        ret, _ = cap.read()
        if not ret:
            break
        time.sleep(0.03)
    cap.release()


@app.route("/camera/start", methods=["POST"])
def camera_start():
    global _cam_active, _cam_thread
    with _cam_lock:
        if _cam_active:
            return jsonify({"status": "already_running"})
        _cam_active = True
        _cam_thread = threading.Thread(target=_camera_loop, daemon=True)
        _cam_thread.start()
    return jsonify({"status": "started"})


@app.route("/camera/stop", methods=["POST"])
def camera_stop():
    global _cam_active
    _cam_active = False
    return jsonify({"status": "stopped"})


def _gen_frames():
    cap = cv2.VideoCapture(0)
    while _cam_active and cap.isOpened():
        ok, frame = cap.read()
        if not ok:
            break
        _, buf = cv2.imencode(".jpg", frame)
        yield (b"--frame\r\n"
               b"Content-Type: image/jpeg\r\n\r\n" + buf.tobytes() + b"\r\n")
        time.sleep(0.03)
    cap.release()


@app.route("/camera/feed")
def camera_feed():
    return Response(_gen_frames(), mimetype="multipart/x-mixed-replace; boundary=frame")


@app.route("/camera/capture", methods=["POST"])
def camera_capture():
    cap = cv2.VideoCapture(0)
    ok, frame = cap.read()
    cap.release()
    if not ok:
        return jsonify({"error": "Camera capture failed"}), 500

    fname = f"cap_{uuid.uuid4().hex[:8]}.jpg"
    path = os.path.join(UPLOAD_DIR, fname)
    cv2.imwrite(path, frame)

    batch, _ = preprocess_frame(frame)
    if batch is None:
        return jsonify({"error": "Preprocessing failed"}), 500

    result = predict(batch, image_path=path)

    # Collect geolocation from JSON body or form
    location = {}
    data = request.get_json(silent=True) or {}
    lat = data.get("latitude") or request.form.get("latitude")
    lng = data.get("longitude") or request.form.get("longitude")
    if lat and lng:
        try:
            location = {
                "lat": float(lat),
                "lng": float(lng),
                "address": data.get("address") or request.form.get("address", "Unknown"),
            }
        except (ValueError, TypeError):
            pass

    record = {
        "id": uuid.uuid4().hex[:12],
        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "filename": fname,
        "image": fname,
        "source": "camera",
        "location": location,
        **result,
    }
    _add_record(record)
    return jsonify(record)


# ===================================================================
# ROUTES — API
# ===================================================================

@app.route("/api/stats")
def api_stats():
    records = _load_history()
    total = len(records)
    fires = sum(1 for r in records if r.get("detailed_label") == "Fire")
    smoke = sum(1 for r in records if r.get("detailed_label") == "Smoke")
    safe = total - fires - smoke
    avg_conf = round(sum(r["confidence"] for r in records) / total, 1) if total else 0
    risk_dist = {}
    for r in records:
        risk_dist[r["risk_level"]] = risk_dist.get(r["risk_level"], 0) + 1

    # Timeline data — group by date
    timeline = {}
    for r in records:
        date = r["timestamp"][:10]  # YYYY-MM-DD
        if date not in timeline:
            timeline[date] = {"fire": 0, "smoke": 0, "safe": 0}
        dl = r.get("detailed_label", "")
        if dl == "Fire":
            timeline[date]["fire"] += 1
        elif dl == "Smoke":
            timeline[date]["smoke"] += 1
        else:
            timeline[date]["safe"] += 1

    return jsonify({
        "total": total,
        "fires": fires,
        "smoke": smoke,
        "safe": safe,
        "avg_confidence": avg_conf,
        "risk_distribution": risk_dist,
        "timeline": timeline,
        "accuracy": {"fire": 96.0, "smoke": 74.0, "no_fire": 90.0, "overall": 86.7},
    })


@app.route("/api/history")
def api_history():
    return jsonify(_load_history())


@app.route("/api/fire-locations")
def api_fire_locations():
    """Return all fire detections that have GPS coordinates."""
    records = _load_history()
    locations = []
    for r in records:
        loc = r.get("location", {})
        if loc.get("lat") and loc.get("lng"):
            locations.append({
                "id": r["id"],
                "lat": loc["lat"],
                "lng": loc["lng"],
                "address": loc.get("address", "Unknown"),
                "label": r["label"],
                "confidence": r["confidence"],
                "timestamp": r["timestamp"],
                "risk_level": r["risk_level"],
            })
    return jsonify(locations)


@app.route("/api/alert", methods=["POST"])
def api_alert():
    """Simulated email alert."""
    data = request.get_json(silent=True) or {}
    email = data.get("email", "admin@forestfire.local")
    return jsonify({
        "status": "sent",
        "message": f"Alert email simulated to {email}",
        "timestamp": datetime.now().isoformat(),
    })


@app.route("/api/history/<record_id>", methods=["DELETE"])
def api_delete_record(record_id):
    """Delete a single detection record."""
    with _history_lock:
        records = _load_history()
        before = len(records)
        records = [r for r in records if r["id"] != record_id]
        if len(records) == before:
            return jsonify({"error": "Record not found"}), 404
        _save_history(records)
    # Also remove the uploaded image if it exists
    for fname in os.listdir(UPLOAD_DIR):
        if record_id in fname:
            try:
                os.remove(os.path.join(UPLOAD_DIR, fname))
            except OSError:
                pass
    return jsonify({"status": "deleted", "id": record_id})


@app.route("/api/history", methods=["DELETE"])
def api_clear_history():
    """Clear all detection history."""
    with _history_lock:
        _save_history([])
    # Clean uploaded files
    for f in os.listdir(UPLOAD_DIR):
        try:
            os.remove(os.path.join(UPLOAD_DIR, f))
        except OSError:
            pass
    return jsonify({"status": "cleared"})


@app.route("/download-report/<record_id>")
def download_report(record_id):
    records = _load_history()
    record = next((r for r in records if r["id"] == record_id), None)
    if record is None:
        return jsonify({"error": "Record not found"}), 404

    report_name = f"report_{record_id}.txt"
    report_path = os.path.join(DATA_DIR, report_name)
    if not os.path.exists(report_path):
        with open(report_path, "w") as fh:
            fh.write(_generate_report(record))

    return send_file(report_path, as_attachment=True, download_name=report_name)


# ===================================================================
# ROUTES — Satellite Fire Monitoring (NASA FIRMS)
# ===================================================================
# Uses NASA FIRMS open active fire data — real satellite fire hotspots
# from VIIRS (Suomi NPP) and MODIS sensors. No API key required.

_sat_cache = {"data": [], "ts": 0, "key": ""}
_SAT_CACHE_TTL = 600  # 10 minutes


@app.route("/satellite")
def satellite_page():
    return render_template("satellite.html")


@app.route("/weather")
def weather_page():
    return render_template("weather.html")


@app.route("/alerts")
def alerts_page():
    return render_template("alerts.html")


@app.route("/statistics")
def statistics_page():
    return render_template("statistics.html")


# Bounding boxes for country filtering (approx lat/lng)
_COUNTRY_BOUNDS = {
    "IND": (6.5, 35.5, 68.0, 97.4),
    "USA": (24.0, 50.0, -125.0, -66.0),
    "AUS": (-44.0, -10.0, 112.0, 154.0),
    "BRA": (-34.0, 5.3, -74.0, -34.8),
    "CAN": (41.7, 83.1, -141.0, -52.6),
    "RUS": (41.0, 82.0, 19.0, 180.0),
    "IDN": (-11.0, 6.1, 95.0, 141.0),
    "GRC": (34.8, 41.7, 19.4, 29.6),
    "PRT": (36.9, 42.2, -9.5, -6.2),
    "ESP": (36.0, 43.8, -9.3, 4.3),
    "TUR": (35.8, 42.1, 26.0, 44.8),
    "CHN": (18.0, 53.5, 73.5, 135.0),
    "ZAF": (-35.0, -22.1, 16.5, 32.9),
    "COL": (-4.2, 12.5, -79.0, -67.0),
    "MEX": (14.5, 32.7, -118.4, -86.7),
}


# ===================================================================
# ROUTES — Weather & Fire Risk Index (Open-Meteo — free, no key)
# ===================================================================

@app.route("/api/weather")
def api_weather():
    """Fetch current weather + calculate Fire Weather Index."""
    city = request.args.get("city", "")
    lat = request.args.get("lat", "")
    lon = request.args.get("lon", "")

    location_name = city or "Unknown"

    # Step 1: Geocode city name to lat/lon using Open-Meteo geocoding
    if not (lat and lon):
        if not city:
            return jsonify({"error": "Provide city or lat/lon"}), 400
        geo_url = f"https://geocoding-api.open-meteo.com/v1/search?name={urllib.parse.quote(city)}&count=1"
        try:
            req = urllib.request.Request(geo_url, headers={"User-Agent": "ForestFireRecognition/1.0"})
            with urllib.request.urlopen(req, timeout=10) as resp:
                geo = json.loads(resp.read().decode("utf-8"))
            results = geo.get("results", [])
            if not results:
                return jsonify({"error": f"City '{city}' not found"}), 404
            lat = results[0]["latitude"]
            lon = results[0]["longitude"]
            location_name = f"{results[0].get('name', city)}, {results[0].get('country_code', '')}"
        except Exception as e:
            return jsonify({"error": f"Geocoding error: {str(e)}"}), 502

    # Step 2: Fetch weather from Open-Meteo
    wx_url = (
        f"https://api.open-meteo.com/v1/forecast?"
        f"latitude={lat}&longitude={lon}"
        f"&current=temperature_2m,relative_humidity_2m,wind_speed_10m,"
        f"precipitation,cloud_cover,surface_pressure,weather_code"
        f"&timezone=auto"
    )
    try:
        req = urllib.request.Request(wx_url, headers={"User-Agent": "ForestFireRecognition/1.0"})
        with urllib.request.urlopen(req, timeout=10) as resp:
            data = json.loads(resp.read().decode("utf-8"))
    except Exception as e:
        return jsonify({"error": f"Weather API error: {str(e)}"}), 502

    cur = data.get("current", {})
    temp_c = cur.get("temperature_2m", 20)
    humidity = cur.get("relative_humidity_2m", 50)
    wind_kmh = cur.get("wind_speed_10m", 0)
    rain_mm = cur.get("precipitation", 0)
    clouds = cur.get("cloud_cover", 0)
    pressure = cur.get("surface_pressure", 1013)
    wmo_code = cur.get("weather_code", 0)

    # WMO weather code to description
    WMO_DESC = {
        0: "Clear Sky", 1: "Mainly Clear", 2: "Partly Cloudy", 3: "Overcast",
        45: "Foggy", 48: "Rime Fog", 51: "Light Drizzle", 53: "Moderate Drizzle",
        55: "Dense Drizzle", 61: "Slight Rain", 63: "Moderate Rain", 65: "Heavy Rain",
        71: "Slight Snow", 73: "Moderate Snow", 75: "Heavy Snow", 80: "Slight Showers",
        81: "Moderate Showers", 82: "Violent Showers", 95: "Thunderstorm",
        96: "Thunderstorm + Hail", 99: "Severe Thunderstorm",
    }
    weather_desc = WMO_DESC.get(wmo_code, "Unknown")

    # --- Calculate simplified Fire Weather Index (0-100) ---
    f_temp = min(max((temp_c - 5) / 40 * 100, 0), 100)
    f_hum = min(max((100 - humidity) / 80 * 100, 0), 100)
    f_wind = min(max(wind_kmh / 60 * 100, 0), 100)
    f_rain = max(100 - rain_mm * 20, 0)

    fwi_score = int(f_temp * 0.35 + f_hum * 0.30 + f_wind * 0.20 + f_rain * 0.15)
    fwi_score = min(max(fwi_score, 0), 100)

    if fwi_score <= 20:
        fwi_level, fwi_desc = "Low", "Fire risk is minimal. Conditions are moist and cool."
        fwi_rec = "Normal activities permitted. Maintain standard fire safety awareness."
    elif fwi_score <= 40:
        fwi_level, fwi_desc = "Moderate", "Some fire risk. Dry patches may exist."
        fwi_rec = "Be cautious with open flames. Monitor local conditions closely."
    elif fwi_score <= 60:
        fwi_level, fwi_desc = "High", "Significant fire risk. Vegetation is drying out."
        fwi_rec = "Avoid open burning. Keep firefighting equipment ready. Alert forest rangers."
    elif fwi_score <= 80:
        fwi_level, fwi_desc = "Very High", "Severe fire risk. Fires can start and spread rapidly."
        fwi_rec = "No open burning. Prepare evacuation plans. Alert emergency services."
    else:
        fwi_level, fwi_desc = "Extreme", "Critical fire danger. Any spark can cause catastrophic fire."
        fwi_rec = "Immediate high alert. Evacuate fire-prone areas. Full emergency readiness."

    return jsonify({
        "location": location_name,
        "updated": cur.get("time", datetime.utcnow().strftime("%Y-%m-%d %H:%M")),
        "weather": {
            "temp_c": temp_c,
            "humidity": humidity,
            "wind_kmh": wind_kmh,
            "visibility_m": 10000,
            "clouds": clouds,
            "pressure": pressure,
            "description": weather_desc,
            "rain_1h": rain_mm,
        },
        "fwi": {
            "score": fwi_score,
            "level": fwi_level,
            "description": fwi_desc,
            "recommendation": fwi_rec,
            "factors": {
                "temperature": round(f_temp, 1),
                "humidity": round(f_hum, 1),
                "wind": round(f_wind, 1),
                "precipitation": round(f_rain, 1),
            },
        },
    })


# ===================================================================
# ROUTES — Email Alert System
# ===================================================================

@app.route("/api/send-alert", methods=["POST"])
def api_send_alert():
    """Send a real email alert via SMTP."""
    data = request.get_json(silent=True) or {}
    email = data.get("email", "").strip()
    smtp_host = data.get("smtp_host", "smtp.gmail.com").strip()
    smtp_port = int(data.get("smtp_port", 587))
    smtp_user = data.get("smtp_user", "").strip()
    smtp_pass = data.get("smtp_pass", "")
    is_test = data.get("test", False)

    if not email:
        return jsonify({"error": "Recipient email is required"}), 400
    if not smtp_user or not smtp_pass:
        return jsonify({"error": "SMTP username and password are required"}), 400
    # Basic validation
    if "@" not in email or "@" not in smtp_user:
        return jsonify({"error": "Invalid email format"}), 400
    # Restrict to known SMTP ports
    if smtp_port not in (25, 465, 587, 2525):
        return jsonify({"error": "Invalid SMTP port"}), 400

    if is_test:
        subject = "Forest Fire Recognition — Test Alert"
        body = (
            "<h2>🔥 Test Alert — Forest Fire Recognition System</h2>"
            "<p>This is a test email to confirm your alert configuration is working correctly.</p>"
            "<p>When a real fire or smoke is detected, you will receive an alert with:</p>"
            "<ul>"
            "<li>Detection type (Fire / Smoke)</li>"
            "<li>Confidence level</li>"
            "<li>Risk assessment</li>"
            "<li>Location coordinates (if available)</li>"
            "<li>Recommended actions</li>"
            "</ul>"
            f"<p><small>Sent at {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</small></p>"
        )
    else:
        det = data.get("detection", {})
        subject = f"🔥 FIRE ALERT — {det.get('label', 'Detection')} — {det.get('confidence', 0):.0f}% Confidence"
        loc_info = ""
        loc = det.get("location", {})
        if loc.get("lat"):
            loc_info = f"<p><strong>Location:</strong> {loc.get('address', 'Unknown')} ({loc['lat']}, {loc['lng']})</p>"
        body = (
            f"<h2>🔥 Forest Fire Alert</h2>"
            f"<p><strong>Detection:</strong> {det.get('label', 'N/A')}</p>"
            f"<p><strong>Confidence:</strong> {det.get('confidence', 0):.1f}%</p>"
            f"<p><strong>Risk Level:</strong> {det.get('risk_level', 'N/A')}</p>"
            f"{loc_info}"
            f"<p><strong>Recommendation:</strong> {det.get('recommendation', 'N/A')}</p>"
            f"<p><small>Detected at {det.get('timestamp', datetime.now().strftime('%Y-%m-%d %H:%M:%S'))}</small></p>"
        )

    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = smtp_user
        msg["To"] = email
        msg.attach(MIMEText(body, "html"))

        if smtp_port == 465:
            server = smtplib.SMTP_SSL(smtp_host, smtp_port, timeout=10)
        else:
            server = smtplib.SMTP(smtp_host, smtp_port, timeout=10)
            server.starttls()
        server.login(smtp_user, smtp_pass)
        server.sendmail(smtp_user, [email], msg.as_string())
        server.quit()
        return jsonify({"status": "sent", "message": f"Email sent to {email}"})
    except smtplib.SMTPAuthenticationError:
        return jsonify({"error": "SMTP authentication failed. Check username/password."}), 401
    except smtplib.SMTPException as e:
        return jsonify({"error": f"SMTP error: {str(e)}"}), 500
    except Exception as e:
        return jsonify({"error": f"Failed to send email: {str(e)}"}), 500


# ===================================================================
# ROUTES — Regional Fire Statistics
# ===================================================================

@app.route("/api/regional-stats")
def api_regional_stats():
    """Aggregate satellite fire data by country for statistics."""
    import time as _time
    now = _time.time()

    # Reuse satellite cache or fetch fresh
    if (now - _sat_cache["ts"] < _SAT_CACHE_TTL and _sat_cache["data"]):
        fires = _sat_cache["data"]
    else:
        # Trigger a fresh fetch via the satellite endpoint logic
        urls = [
            "https://firms.modaps.eosdis.nasa.gov/data/active_fire/suomi-npp-viirs-c2/csv/SUOMI_VIIRS_C2_Global_24h.csv",
            "https://firms.modaps.eosdis.nasa.gov/data/active_fire/modis-c6.1/csv/MODIS_C6_1_Global_24h.csv",
        ]
        fires = []
        for url in urls:
            try:
                req = urllib.request.Request(url, headers={"User-Agent": "ForestFireRecognition/1.0"})
                with urllib.request.urlopen(req, timeout=20) as resp:
                    raw = resp.read().decode("utf-8")
                reader = csv.DictReader(io.StringIO(raw))
                for i, row in enumerate(reader):
                    if i >= 8000:
                        break
                    try:
                        fires.append({
                            "lat": float(row.get("latitude", 0)),
                            "lng": float(row.get("longitude", 0)),
                            "confidence": row.get("confidence", "nominal"),
                            "frp": float(row.get("frp", 0) or 0),
                        })
                    except (ValueError, TypeError):
                        continue
            except Exception:
                continue
        if fires:
            _sat_cache["data"] = fires
            _sat_cache["ts"] = now

    # Aggregate per country
    country_stats = {}
    for code, bounds in _COUNTRY_BOUNDS.items():
        lat_min, lat_max, lng_min, lng_max = bounds
        matched = [f for f in fires if lat_min <= f["lat"] <= lat_max and lng_min <= f["lng"] <= lng_max]
        if not matched:
            continue
        frps = [f["frp"] for f in matched if f["frp"] > 0]
        high_conf = sum(1 for f in matched
                        if str(f["confidence"]).lower() in ("high", "h")
                        or (str(f["confidence"]).isdigit() and int(f["confidence"]) >= 80))
        country_stats[code] = {
            "count": len(matched),
            "high_confidence": high_conf,
            "avg_frp": round(sum(frps) / len(frps), 2) if frps else 0,
            "max_frp": round(max(frps), 2) if frps else 0,
        }

    return jsonify({
        "countries": country_stats,
        "total_worldwide": len(fires),
        "timestamp": datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC"),
    })


@app.route("/api/satellite-fires")
def api_satellite_fires():
    """
    Fetch recent fire hotspots from NASA FIRMS VIIRS open data.
    Returns list of active fire points.
    Params:
      ?country=IND  — ISO3 country code (default: world)
                      filtering is done via bounding box
    """
    import time as _time
    now = _time.time()

    country = request.args.get("country", "world")

    # Check cache (use same worldwide data, filter client-side by country)
    if (now - _sat_cache["ts"] < _SAT_CACHE_TTL and _sat_cache["data"]):
        fires = _sat_cache["data"]
    else:
        # Fetch from NASA FIRMS open data (24h, updated hourly)
        urls = [
            "https://firms.modaps.eosdis.nasa.gov/data/active_fire/suomi-npp-viirs-c2/csv/SUOMI_VIIRS_C2_Global_24h.csv",
            "https://firms.modaps.eosdis.nasa.gov/data/active_fire/modis-c6.1/csv/MODIS_C6_1_Global_24h.csv",
        ]

        fires = []
        for url in urls:
            try:
                req = urllib.request.Request(url, headers={"User-Agent": "ForestFireRecognition/1.0"})
                with urllib.request.urlopen(req, timeout=20) as resp:
                    raw = resp.read().decode("utf-8")

                reader = csv.DictReader(io.StringIO(raw))
                for i, row in enumerate(reader):
                    if i >= 8000:
                        break
                    try:
                        lat = float(row.get("latitude", 0))
                        lng = float(row.get("longitude", 0))
                        confidence = row.get("confidence", "nominal")
                        bright = row.get("bright_ti4", row.get("brightness", ""))
                        frp = row.get("frp", "0")
                        acq_date = row.get("acq_date", "")
                        acq_time = row.get("acq_time", "")
                        fires.append({
                            "lat": lat,
                            "lng": lng,
                            "confidence": confidence,
                            "brightness": bright,
                            "frp": float(frp) if frp else 0,
                            "date": acq_date,
                            "time": acq_time,
                            "satellite": row.get("satellite", "N/A"),
                        })
                    except (ValueError, TypeError):
                        continue
            except Exception:
                continue

        if fires:
            _sat_cache["data"] = fires
            _sat_cache["ts"] = now

    # Filter by country bounding box
    if country != "world" and country in _COUNTRY_BOUNDS:
        lat_min, lat_max, lng_min, lng_max = _COUNTRY_BOUNDS[country]
        fires = [f for f in fires
                 if lat_min <= f["lat"] <= lat_max and lng_min <= f["lng"] <= lng_max]

    return jsonify(fires[:5000])


# ===================================================================
# Error handlers
# ===================================================================

@app.errorhandler(404)
def page_not_found(_):
    return render_template("index.html"), 404


@app.errorhandler(413)
def file_too_large(_):
    return jsonify({"error": "File exceeds 16 MB limit"}), 413


# ===================================================================
# Entry point
# ===================================================================

if __name__ == "__main__":
    print("=" * 56)
    print("  Forest Fire Recognition System")
    print("  Starting server …")
    print("=" * 56)
    app.run(host="0.0.0.0", port=5000, debug=True, threaded=True)
